/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DB_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "UploadsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}